project:
  type: website
  output-dir: docs

website:
  title: "Projeto e Análise de Algoritmos I"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercicios.qmd
        text: Exercícios

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    include-after-body: _footer.html
